// ═══════════════════════════════════════════
// 📄 README Generator - 프로필 README 자동 생성
// ═══════════════════════════════════════════

import * as fs from 'fs';
import * as path from 'path';
import { GitProConfig } from '../types';
import { ModuleResult } from './module-runner';

const GITPRO_START = '<!-- GITPRO:START -->';
const GITPRO_END = '<!-- GITPRO:END -->';

/** 모듈별 제목 */
const MODULE_TITLES: Record<string, { icon: string; title: string }> = {
  'trading-card': { icon: '🃏', title: 'Dev Trading Card' },
  'code-dna': { icon: '🧬', title: 'Code DNA' },
  chronicle: { icon: '📜', title: 'Dev Chronicle' },
  'code-pet': { icon: '🐾', title: 'Code Pet' },
  constellation: { icon: '🌌', title: 'Commit Constellation' },
  'dev-city': { icon: '🏙️', title: 'Dev City' },
};

/**
 * README.md를 업데이트합니다.
 * GITPRO:START ~ GITPRO:END 사이의 내용을 교체합니다.
 */
export function updateReadme(config: GitProConfig, results: ModuleResult[]): void {
  const readmePath = path.resolve(process.cwd(), 'README.md');

  // 기존 README 로드 또는 새로 생성
  let readmeContent: string;
  if (fs.existsSync(readmePath)) {
    readmeContent = fs.readFileSync(readmePath, 'utf-8');
  } else {
    readmeContent = generateNewReadme(config);
  }

  // GITPRO 섹션 생성
  const gitproSection = generateGitproSection(config, results);

  // 기존 GITPRO 섹션 교체 또는 추가
  if (readmeContent.includes(GITPRO_START) && readmeContent.includes(GITPRO_END)) {
    const startIdx = readmeContent.indexOf(GITPRO_START);
    const endIdx = readmeContent.indexOf(GITPRO_END) + GITPRO_END.length;
    readmeContent =
      readmeContent.substring(0, startIdx) +
      gitproSection +
      readmeContent.substring(endIdx);
  } else {
    readmeContent += '\n\n' + gitproSection;
  }

  fs.writeFileSync(readmePath, readmeContent, 'utf-8');
  console.log('📄 README.md 업데이트 완료!');
}

/**
 * 새 README.md 기본 내용을 생성합니다.
 */
function generateNewReadme(config: GitProConfig): string {
  const headerText = config.readme.header.text || `Hello, I'm ${config.username}! 👋`;

  return `# ${headerText}

${GITPRO_START}
${GITPRO_END}
`;
}

/**
 * GITPRO 섹션 마크다운을 생성합니다.
 */
function generateGitproSection(config: GitProConfig, results: ModuleResult[]): string {
  const layout = config.readme.layout || 'vertical';

  switch (layout) {
    case 'grid':
      return generateGridLayout(results);
    case 'tabs':
      return generateTabsLayout(results);
    case 'vertical':
    default:
      return generateVerticalLayout(results);
  }
}

/**
 * 세로 나열 레이아웃
 */
function generateVerticalLayout(results: ModuleResult[]): string {
  let markdown = `${GITPRO_START}\n\n<div align="center">\n\n`;

  for (const result of results) {
    const info = MODULE_TITLES[result.id] || { icon: '📦', title: result.id };
    markdown += `### ${info.icon} ${info.title}\n\n`;
    markdown += `<img src="./output/${result.id}.svg" alt="${info.title}" />\n\n`;
  }

  markdown += `</div>\n\n`;
  markdown += `<p align="center"><sub>🎮 Generated by <a href="https://github.com/Sangyeonglee353/gitpro">gitpro</a></sub></p>\n\n`;
  markdown += GITPRO_END;

  return markdown;
}

/**
 * 2열 그리드 레이아웃
 */
function generateGridLayout(results: ModuleResult[]): string {
  let markdown = `${GITPRO_START}\n\n<div align="center">\n\n`;

  // 2개씩 묶어서 테이블로
  for (let i = 0; i < results.length; i += 2) {
    const left = results[i];
    const right = results[i + 1];
    const leftInfo = MODULE_TITLES[left.id] || { icon: '📦', title: left.id };

    if (right) {
      const rightInfo = MODULE_TITLES[right.id] || { icon: '📦', title: right.id };
      markdown += `<table><tr>\n`;
      markdown += `<td align="center">\n\n### ${leftInfo.icon} ${leftInfo.title}\n<img src="./output/${left.id}.svg" width="400" />\n\n</td>\n`;
      markdown += `<td align="center">\n\n### ${rightInfo.icon} ${rightInfo.title}\n<img src="./output/${right.id}.svg" width="400" />\n\n</td>\n`;
      markdown += `</tr></table>\n\n`;
    } else {
      markdown += `### ${leftInfo.icon} ${leftInfo.title}\n\n`;
      markdown += `<img src="./output/${left.id}.svg" />\n\n`;
    }
  }

  markdown += `</div>\n\n`;
  markdown += `<p align="center"><sub>🎮 Generated by <a href="https://github.com/Sangyeonglee353/gitpro">gitpro</a></sub></p>\n\n`;
  markdown += GITPRO_END;

  return markdown;
}

/**
 * 탭(접기) 레이아웃
 */
function generateTabsLayout(results: ModuleResult[]): string {
  let markdown = `${GITPRO_START}\n\n<div align="center">\n\n`;

  for (let i = 0; i < results.length; i++) {
    const result = results[i];
    const info = MODULE_TITLES[result.id] || { icon: '📦', title: result.id };
    const isOpen = i === 0 ? ' open' : '';

    markdown += `<details${isOpen}>\n`;
    markdown += `<summary>${info.icon} ${info.title}</summary>\n\n`;
    markdown += `<img src="./output/${result.id}.svg" alt="${info.title}" />\n\n`;
    markdown += `</details>\n\n`;
  }

  markdown += `</div>\n\n`;
  markdown += `<p align="center"><sub>🎮 Generated by <a href="https://github.com/Sangyeonglee353/gitpro">gitpro</a></sub></p>\n\n`;
  markdown += GITPRO_END;

  return markdown;
}
